### ISSUE TITLE
csv files should use commas and not semicolons

### ISSUE THREAD

**Issue by konstin** [Rostlab/VESPA#4]
currently, VESPA outputs semicolon in its .csv files, while csv files are supposed to be comma separated (https://www.rfc-editor.org/rfc/rfc4180). This means that e.g. `pandas.read_csv()` fails to parse these files.

E.g. instead of 

```csv
Mutant;VESPAl
M0A;0.5637843671016098
M0L;0.4295767637843729
```

the output should be 

```csv
Mutant,VESPAl
M0A,0.5637843671016098
M0L,0.4295767637843729
```

**Comment by t03i** [comment]
Hey @konstin,

Thanks for being patient, and thanks for bringing it up!
Given that we store numeric values in the CSV format, we opted for using semicolons as column separators
(Just to make extra sure there are no mishaps with localization). For the files without specific description, we specified semicolon as separator.

Pandas can handle the format by specifying `sep = ';'`.
