### ISSUE TITLE
CalledProcessError: Command '

### ISSUE THREAD

**Issue by skim245** [Rostlab/VESPA#6]
Dear Rostlab 

I'm getting an "AttributeError: 'NoneType' object has no attribute 'get'
Below is the error I get. 
Vespa works nicely with a smaller subset (n of 13) of fata but throws an error with n of 8000.  

Finished Conservation Prediction!
########################### Start Vespa Predictions ############################
/usr/local/lib/python3.8/dist-packages/sklearn/base.py:329: UserWarning: Trying to unpickle estimator LogisticRegression from version 0.22.2.post1 when using version 1.0.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/modules/model_persistence.html#security-maintainability-limitations
  warnings.warn(
Blosum Lookup:   1% 74426/9052365 [00:00<00:42, 213019.86it/s]
Traceback (most recent call last):
  File "/usr/local/bin/vespa", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/vespa/scripts/meta.py", line 286, in main
    run_vespa(**vespa_arguments)
  File "/usr/local/lib/python3.8/dist-packages/vespa/scripts/vespa_run.py", line 128, in run_vespa
    output = predictor.generate_predictions(mutation_gen=mutation_gen, **input)
  File "/usr/local/lib/python3.8/dist-packages/vespa/predict/vespa.py", line 249, in generate_predictions
    input = self.__generate_input(mutation_gen, conservations, logodds)
  File "/usr/local/lib/python3.8/dist-packages/vespa/predict/vespa.py", line 219, in __generate_input
    input["blosum_vec"] = self.__generate_blosum_vec(mutation_gen)
  File "/usr/local/lib/python3.8/dist-packages/vespa/predict/vespa.py", line 160, in __generate_blosum_vec
    vector[idx] = self.subst_matrix.get(fromAA).get(toAA)
AttributeError: 'NoneType' object has no attribute 'get'
---------------------------------------------------------------------------
CalledProcessError                        Traceback (most recent call last)
[<ipython-input-7-2a3aec966942>](https://localhost:8080/#) in <module>
----> 1 get_ipython().run_cell_magic('shell', '', "\nvespa /content/drive/MyDrive/SH/data/'PRO extraction.fasta' --prott5_weights_cache /content/drive/MyDrive/SH/data/cache --vespa_output_directory /content/drive/MyDrive/SH/data/output\n")

2 frames
[/usr/local/lib/python3.8/dist-packages/google/colab/_system_commands.py](https://localhost:8080/#) in check_returncode(self)
    132   def check_returncode(self):
    133     if self.returncode:
--> 134       raise subprocess.CalledProcessError(
    135           returncode=self.returncode, cmd=self.args, output=self.output)
    136 

CalledProcessError: Command '
vespa /content/drive/MyDrive/SH/data/'PRO extraction.fasta' --prott5_weights_cache /content/drive/MyDrive/SH/data/cache --vespa_output_directory /content/drive/MyDrive/SH/data/output
' returned non-zero exit status 1.

**Comment by skim245** [comment]
and i also have another quick question, if we could use one of the output with PyMol to recolor the conserved region of interest.

**Comment by C-Marquet** [comment]
@skim245 regarding the coloring, if I understand you correctly, you want to highlight a protein based on the 9 conservation classes? in this notebook https://github.com/Rostlab/TMvis/blob/main/TMvis/TMvis.ipynb, we applied a color code for either AlphaFold confidence or transmembrane regions. This could be used for conservation scores as well, let me know if you need help adjusting it! :)
