### ISSUE TITLE
Multiple point mutations input file

### ISSUE THREAD

**Issue by tekpinar** [Rostlab/VESPA#9]
Hi,
As you explained in your README page, one must prepare a mutation file for each single point mutation in the following format:
YAP1_D170N, where protein name is separated from the single point mutation with an underscore. 
I was wondering what is the correct format for the multiple point mutations: For example, what is the proper format if I want to see effect  of a double mutation such as D170N-I193K? 
Thanks in advance,
Mustafa

**Comment by C-Marquet** [comment]
Sorry about the (very) late reply. Double mutations are unfortunately not supported when providing a mutation file.
